apiVersion: v1
kind: Cluster
metadata:
    name: demo-cluster-01
    region: local-1
spec:
    driver:
        source: ./modules/demo-cluster
        version: 0.1.0
    params:
        node_count: "3"
        node_size: small
    workflows:
        onCreate:
            - setup-demo
        onDelete:
            - cleanup-demo
