apiVersion: v1
kind: Cluster
metadata:
    name: demo-civo-02
    region: NYC2
spec:
    driver:
        source: ./modules/demo-civo
        version: 0.1.0
    params:
        applications: Traefik
        civo_organization: default
        node_count: "5"
        node_size: g4s.kube.small
        region: NYC1
    driverOutputs:
        HYVE_ACCESS_PORT: "6443"
        HYVE_CLUSTER_STATUS: ACTIVE
        HYVE_ENDPOINT: https://demo-civo.local/demo-civo-02
        HYVE_LAST_PARAMS_HASH: 4222b3a3e20afbc4df6779881fc61ecd20ada34eb7011a9ed41457fc6dd9fa15
        HYVE_MASTER_IP: 10.0.1.10
        HYVE_NODE_COUNT: "5"
    workflows:
        onCreate:
            - setup-demo
        onDelete:
            - cleanup-demo
