apiVersion: v1
kind: Cluster
metadata:
  name: local-k3d-01
  region: local
spec:
  driver:
    source: ./modules/k3d
    version: 1.0.0
  params:
    agent_count: "1"
  workflows:
    onCreate:
      - setup-demo
    onDelete:
      - cleanup-demo
  resources:
    - name: whoami
      source: ./resource-files/whoami/manifest.yaml
