apiVersion: v1
kind: Cluster
metadata:
    name: local-k3d-01
    region: local
spec:
    driver:
        source: ./modules/k3d
        version: 1.0.0
    params:
        agent_count: "1"
    driverOutputs:
        HYVE_CLUSTER_ID: k3d-local-k3d-01
        HYVE_LAST_PARAMS_HASH: 0239595d44c09deb73e830e0a4802fca81eccc5a69dc620fb3a8b1c170c88831
        HYVE_NODE_COUNT: "1"
    workflows:
        onCreate:
            - setup-demo
        onDelete:
            - cleanup-demo
