apiVersion: v1
kind: Workflow
metadata:
  name: demo-gke-status
spec:
  jobs:
    - name: status
      steps:
        - name: check-state
          run: |
            if [ -f ".state/demo-gke/$HYVE_CLUSTER_NAME" ]; then
              echo "HYVE_CLUSTER_STATUS=ACTIVE"
            else
              echo "HYVE_CLUSTER_STATUS=NOT_FOUND"
            fi
