apiVersion: v1
kind: Workflow
metadata:
  name: demo-aws-eks-delete
spec:
  jobs:
    - name: delete
      steps:
        - name: remove-state
          run: |
            rm -f ".state/demo-aws-eks/$HYVE_CLUSTER_NAME"
            echo "HYVE_CLUSTER_STATUS=NOT_FOUND"
