apiVersion: v1
kind: Workflow
metadata:
  name: demo-aws-eks-scale
spec:
  jobs:
    - name: scale
      steps:
        - name: update-state
          run: |
            if [ -f ".state/demo-aws-eks/$HYVE_CLUSTER_NAME" ]; then
              echo "vpc=$HYVE_PARAM_VPC_ID role=$HYVE_PARAM_NODE_ROLE_NAME type=$HYVE_PARAM_INSTANCE_TYPE" > ".state/demo-aws-eks/$HYVE_CLUSTER_NAME"
            fi
            echo "HYVE_INSTANCE_TYPE=${HYVE_PARAM_INSTANCE_TYPE:-t3.medium}"
